version: '3'
services:
  nodejs:
    image: node:${NODE_VERSION}
    working_dir: /code
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    ports:
      - "4200:4200"
      - "3333:3333"
    command: ["bash"]
